#!/bin/bash

set -e

ninja -C build clean

cmake -G Ninja -S ports/origins/llvm-project/runtimes -B .llvm-build-libs \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SYSTEM_NAME=Generic \
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_COMPILER_TARGET=x86_64-radish \
        -DCMAKE_CXX_COMPILER_TARGET=x86_64-radish \
        -DCMAKE_SYSROOT="$1" \
        -DCMAKE_INSTALL_PREFIX="$1/usr" \
        -DCMAKE_C_FLAGS="-D__radishos__ -Wno-error=return-type -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE" \
        -DCMAKE_CXX_FLAGS="-D__radishos__ -Wno-error=return-type -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE" \
        -DLLVM_ENABLE_RUNTIMES="libunwind;libcxxabi;libcxx;compiler-rt" \
        -DCXX_SUPPORTS_WERROR_EQ_RETURN_TYPE_FLAG=0 \
        -DLIBCXX_ENABLE_SHARED=OFF \
        -DLIBCXXABI_ENABLE_SHARED=OFF \
        -DLIBUNWIND_ENABLE_SHARED=OFF \
        -DLIBCXX_ENABLE_THREADS=OFF \
        -DLIBCXXABI_ENABLE_THREADS=OFF \
        -DLIBUNWIND_ENABLE_THREADS=OFF \
        -DLIBUNWIND_IS_BAREMETAL=ON \
        -DLIBUNWIND_ENABLE_CROSS_UNWINDING=OFF \
        -DLIBCXX_ENABLE_FILESYSTEM=OFF \
        -DLIBCXX_ENABLE_WIDE_CHARACTERS=OFF \
        -DLIBCXX_ENABLE_LOCALIZATION=OFF \
        -DLIBCXX_ENABLE_MONOTONIC_CLOCK=OFF \
        -DLIBCXX_INCLUDE_TESTS=OFF \
        -DLIBCXXABI_INCLUDE_TESTS=OFF \
        -DLIBUNWIND_INCLUDE_TESTS=OFF \
        -DCOMPILER_RT_BUILD_BUILTINS=ON \
        -DCOMPILER_RT_BAREMETAL_BUILD=ON \
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
        -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
        -DCOMPILER_RT_BUILD_XRAY=OFF \
        -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
        -DCOMPILER_RT_BUILD_PROFILE=OFF \
        -DCOMPILER_RT_BUILD_MEMPROF=OFF \
        -DCOMPILER_RT_BUILD_ORC=OFF \
        -DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
        -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-radish \
        -DDEFAULT_SYSROOT=/home/adrien/.local \
        -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
        -DCLANG_DEFAULT_RTLIB=compiler-rt \
        -DCLANG_DEFAULT_UNWINDLIB=libunwind \
        -DCLANG_DEFAULT_LINKER=lld \
        -DLLVM_TOOLCHAIN_TOOL_PREFIX=x86_64-radish-

ninja -C build install-compiler-rt install-cxx install-cxxabi install-unwind