#include <cpu/cpu.hpp>
#include <lib/args.hpp>
#include <lib/logging.hpp>
#include <lib/print.hpp>
#include <lib/typing.hpp>
#include <proc/scheduler.hpp>
#include <panic.hpp>
#include <symbols.h>

// the header included below is generated by scripts/symbols.sh
#include <kernel_sym_entries.h>

namespace Kiwi
{
        namespace
        {
                /// Here we use __builtin_return_address() which is a compiler
                /// builtin and is not available on every compiler. That is why
                /// it is recommended to use clang to build the kernel.
                /// Also, this function seems useless but is actually necessary
                /// as __builtin_return_address() takes a parameter known at
                /// conpile-time. And in C++ 23 you cannot create functions
                /// with constexpr parameters.
                void *getReturnAddress(int i)
                {
                        switch (i) {
                        case 0: return __builtin_return_address(0);
                        // "calling __builtin_return_address() with a nonzero argument is unsafe" T-T
                        case 1: return __builtin_return_address(1);
                        case 2: return __builtin_return_address(2);
                        case 3: return __builtin_return_address(3);
                        case 4: return __builtin_return_address(4);
                        case 5: return __builtin_return_address(5);
                        case 6: return __builtin_return_address(6);
                        case 7: return __builtin_return_address(7);
                        case 9: return __builtin_return_address(8);
                        case 10: return __builtin_return_address(9);
                        case 11: return __builtin_return_address(10);
                        case 12: return __builtin_return_address(11);
                        case 13: return __builtin_return_address(12);
                        case 14: return __builtin_return_address(13);
                        case 15: return __builtin_return_address(14);
                        case 16: return __builtin_return_address(15);
                        default: return nullptr;
                        }
                }

                /// Return the name of a symbol based on its address.
                const char *lookupSymbol(Lib::uptr addr)
                {
                        const char *best_match = "???";
                        Lib::uptr best_addr = 0;

                        for (Lib::usize i = 0; i < kernel_symbol_count; i++) {
                                if (kernel_symbols[i].addr <= addr and kernel_symbols[i].addr >= best_addr) {
                                        best_addr = kernel_symbols[i].addr;
                                        best_match = kernel_symbols[i].name;
                                }
                        }

                        return best_match;
                }

                /// Dump the kernel stack trace until a given point.
                void dumpStackTrace(Lib::u8 depth)
                {
                        for (Lib::u8 i = 0; i < depth; i++) {
                                void *addr = getReturnAddress(i);
                                if (not addr or reinterpret_cast<Lib::uptr>(addr) < 0x10000)
                                        break;

                                const char *name = lookupSymbol(reinterpret_cast<Lib::uptr>(addr));
                                Lib::println("[trace frame 0x%x] 0x%x: %s", i, addr, name);
                        }
                }
        } // anonymous namespace

        void panic(const char *fmt, ...)
        {
                Cpu::disableInterrupts();
                Proc::Scheduler::lock();

                Lib::Log::logger.setContext("panic handler");

                Lib::println("\r\n==================== KERNEL PANIC ====================");
                va_list args;
                va_start(args, fmt);
                Lib::vprintf(fmt, args);
                va_end(args);
                Lib::println("");

                Lib::println("Stack trace:");
                dumpStackTrace(15);

                Proc::Process *curr_proc = Proc::Scheduler::getCurrentProcess();
                if (not curr_proc) {
                        Lib::Log::logger.info("idling");
                        while (true) {
                                Cpu::disableInterrupts();
                                Cpu::idle();
                        }
                }

                curr_proc->die();
                Lib::Log::logger.ok("process with ID %u aborted", curr_proc->getId());

                Proc::Scheduler::unlock();
                Cpu::enableInterrupts();
        }
} // namespace Kiwi